import React, { useState } from 'react';
import { useCart } from '../context/CartContext';
import './CustomerDetails.css';

const CustomerDetails = ({ onBack }) => {
  const { cartItems, getCartTotal, clearCart } = useCart();
  const [formData, setFormData] = useState({
    name: '',
    address: '',
    pincode: '',
    phone: '',
    gstNo: ''
  });
  const [isSubmitting, setIsSubmitting] = useState(false);

  // GitHub Configuration
  const GITHUB_CONFIG = {
    owner: 'shazadkhan123456789',
    repo: 'SK-Steel-Furniture',
    branch: 'main'
  };

  const generateOrderData = () => {
    return {
      id: `ORDER-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      customer: formData,
      items: cartItems.map(item => ({
        id: item.id,
        name: item.name,
        material: item.material,
        quantity: item.quantity,
        unitPrice: item.retailPrice,
        totalPrice: item.retailPrice * item.quantity
      })),
      summary: {
        totalItems: cartItems.reduce((sum, item) => sum + item.quantity, 0),
        totalAmount: getCartTotal(),
        orderDate: new Date().toLocaleString('en-IN', {
          timeZone: 'Asia/Kolkata',
          year: 'numeric',
          month: '2-digit',
          day: '2-digit',
          hour: '2-digit',
          minute: '2-digit',
          second: '2-digit'
        })
      }
    };
  };

  const handleInputChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const validateForm = () => {
    if (!formData.name.trim()) {
      alert('Please enter customer name');
      return false;
    }
    if (!formData.address.trim()) {
      alert('Please enter address');
      return false;
    }
    if (!formData.pincode.trim() || !/^\d{6}$/.test(formData.pincode)) {
      alert('Please enter a valid 6-digit pincode');
      return false;
    }
    if (!formData.phone.trim() || !/^\d{10}$/.test(formData.phone)) {
      alert('Please enter a valid 10-digit phone number');
      return false;
    }
    return true;
  };

  const createGitHubIssue = async (orderData) => {
    const issueTitle = `🛋️ ORDER: ${formData.name} - ${formData.phone} - ₹${getCartTotal().toLocaleString()}`;
    
    const issueBody = `
## 🛋️ NEW FURNITURE ORDER
**SK Steel And Furniture**

---

### 📋 ORDER INFORMATION
**Order ID:** \`${orderData.id}\`  
**Order Date:** ${orderData.summary.orderDate}  
**Order Status:** 🟢 **RECEIVED**

---

### 👤 CUSTOMER DETAILS
**Name:** ${formData.name}  
**Phone:** 📞 ${formData.phone}  
**Address:** 🏠 ${formData.address}  
**Pincode:** 📍 ${formData.pincode}  
**GST Number:** ${formData.gstNo || 'Not Provided'}

---

### 🛒 ORDER ITEMS

| Product | Material | Quantity | Unit Price | Total Price |
|---------|----------|----------|------------|-------------|
${orderData.items.map(item => 
  `| ${item.name} | ${item.material} | ${item.quantity} | ₹${item.unitPrice.toLocaleString()} | **₹${item.totalPrice.toLocaleString()}** |`
).join('\n')}

---

### 💰 ORDER SUMMARY

**Total Items:** ${orderData.summary.totalItems}  
**Grand Total:** **₹${orderData.summary.totalAmount.toLocaleString()}**

---

### 🔄 NEXT STEPS
1. ✅ Order received automatically
2. 📧 Email notification sent to business
3. 👨‍💼 Sales team to contact customer
4. 🚚 Arrange delivery

---

*Automatically generated by SK Steel Furniture Partner Portal*  
*Order ID: ${orderData.id}*
    `.trim();

    // GitHub API call to create issue
    const response = await fetch(
      `https://api.github.com/repos/${GITHUB_CONFIG.owner}/${GITHUB_CONFIG.repo}/issues`,
      {
        method: 'POST',
        headers: {
          'Authorization': `token ${process.env.REACT_APP_GH_TOKEN}`,
          'Content-Type': 'application/json',
          'Accept': 'application/vnd.github.v3+json',
          'X-GitHub-Api-Version': '2022-11-28'
        },
        body: JSON.stringify({
          title: issueTitle,
          body: issueBody,
          labels: ['order', 'automated', 'pending'],
          assignees: [] // You can add specific usernames here
        })
      }
    );

    if (!response.ok) {
      const errorData = await response.json();
      console.error('GitHub API Error:', errorData);
      throw new Error(`GitHub API: ${errorData.message || 'Unknown error'}`);
    }

    const result = await response.json();
    console.log('GitHub Issue created:', result);
    return result;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!validateForm()) return;

    setIsSubmitting(true);

    try {
      const orderData = generateOrderData();
      
      console.log('Creating GitHub Issue for order:', orderData);

      // Create GitHub Issue
      const issueResult = await createGitHubIssue(orderData);
      const issueNumber = issueResult.number;
      const issueUrl = issueResult.html_url;

      // Show success message with issue details
      alert(`🎉 ORDER PLACED SUCCESSFULLY!

✅ Order #${orderData.id} Created
✅ GitHub Issue #${issueNumber} Opened
✅ System Processing Automatically
✅ Email Notification Sent

📋 Order Details:
• Order ID: ${orderData.id}
• GitHub Issue: #${issueNumber}
• Customer: ${formData.name}
• Phone: ${formData.phone}
• Total: ₹${getCartTotal().toLocaleString()}
• Items: ${cartItems.length} product(s)

🔄 Next Steps:
1. Sales team will contact you within 24 hours
2. Delivery will be scheduled
3. You can track order via Issue #${issueNumber}

Thank you for choosing SK Steel And Furniture!
      `);
      
      // Clear cart and go back
      clearCart();
      onBack();
      
    } catch (error) {
      console.error('Order submission error:', error);
      
      // Enhanced error handling
      let errorMessage = 'Failed to create order automatically. ';
      
      if (error.message.includes('401') || error.message.includes('Bad credentials')) {
        errorMessage += 'Authentication failed. Please check GitHub token configuration.';
      } else if (error.message.includes('404')) {
        errorMessage += 'Repository not found. Please check repository name.';
      } else if (error.message.includes('rate limit')) {
        errorMessage += 'Rate limit exceeded. Please try again in a few minutes.';
      } else {
        errorMessage += error.message;
      }
      
      alert(`❌ ${errorMessage}
      
Your order details have been saved locally. Please contact support with Order ID.`);
      
      // Fallback: Save order locally
      const orderData = generateOrderData();
      localStorage.setItem('last_order', JSON.stringify(orderData));
      
      // Still clear cart
      clearCart();
      onBack();
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="customer-details-container">
      <div className="customer-header">
        <button className="back-btn" onClick={onBack}>
          ← Back to Cart
        </button>
        <h2>Customer Details</h2>
      </div>

      <div className="customer-form-container">

        <form onSubmit={handleSubmit} className="customer-form">
          <div className="form-group">
            <label htmlFor="name">Full Name *</label>
            <input
              type="text"
              id="name"
              name="name"
              value={formData.name}
              onChange={handleInputChange}
              required
              placeholder="Enter customer full name"
            />
          </div>

          <div className="form-group">
            <label htmlFor="address">Delivery Address *</label>
            <textarea
              id="address"
              name="address"
              value={formData.address}
              onChange={handleInputChange}
              required
              placeholder="Enter complete delivery address"
              rows="3"
            />
          </div>

          <div className="form-row">
            <div className="form-group">
              <label htmlFor="pincode">Pincode *</label>
              <input
                type="text"
                id="pincode"
                name="pincode"
                value={formData.pincode}
                onChange={handleInputChange}
                required
                placeholder="6-digit pincode"
                maxLength="6"
                pattern="\d{6}"
              />
            </div>

            <div className="form-group">
              <label htmlFor="phone">Phone Number *</label>
              <input
                type="tel"
                id="phone"
                name="phone"
                value={formData.phone}
                onChange={handleInputChange}
                required
                placeholder="10-digit phone number"
                maxLength="10"
                pattern="\d{10}"
              />
            </div>
          </div>

          <div className="form-group">
            <label htmlFor="gstNo">GST Number (Optional)</label>
            <input
              type="text"
              id="gstNo"
              name="gstNo"
              value={formData.gstNo}
              onChange={handleInputChange}
              placeholder="Enter GST number if available"
            />
          </div>

          <div className="order-summary">
            <h3>Order Summary</h3>
            {cartItems.map(item => (
              <div key={item.id} className="order-item">
                <span>{item.name} x {item.quantity}</span>
                <span>₹{(item.retailPrice * item.quantity).toLocaleString()}</span>
              </div>
            ))}
            <div className="order-total">
              <strong>Total: ₹{getCartTotal().toLocaleString()}</strong>
            </div>
          </div>

          <button 
            type="submit" 
            className="place-order-btn"
            disabled={isSubmitting}
          >
            {isSubmitting ? '🔄 Your Order is Under Process...' : '🚀 Place Order'}
          </button>
        </form>
      </div>
    </div>
  );
};

export default CustomerDetails;